name: Test
on: 
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: barneschism/hello-world-docker-action@v1.1.0
        with:
          who-to-greet: 'steve'
